# 02 Drawings Preprocess - VIA 57 West

## Case Information

* **Case ID**: `case_02_via_57_west`
* **Project Name**: VIA 57 West
* **Architect**: BIG - Bjarke Ingels Group
* **Location**: Manhattan, New York City, USA
* **Building Type**: High-rise Residential
* **Preprocess Type**: Architectural Drawings / Diagrams
* **Input Materials**:

  * Longitudinal section
  * 4th floor plan
  * Courtyard / amenity plan
  * Massing transformation diagram
  * Aerial context image

---

## 1. Purpose of Drawing Preprocess

This drawing preprocess translates architectural drawings and diagrams into textual information for Precedent DNA analysis.

The goal is to extract:

1. **Architectural vocabulary**
   Important spatial elements, building components, and residential typologies.

2. **Spatial relationship descriptions**
   How the tower, courtyard, residential units, circulation, amenities, and urban edges relate to each other.

3. **Overall spatial logic**
   The design logic behind the hybrid form: a building that combines the density of a skyscraper with the communal space of a courtyard block.

---

## 2. Drawing / Diagram Inventory

### 2.1 Longitudinal Section

The longitudinal section shows the building as a sloped triangular or tetrahedral mass. One corner rises to a high point, while the mass slopes down toward the lower edge. The section reveals the stacking of residential floors, the internal courtyard space, and the relationship between the sloping exterior envelope and the repeated unit floors.

The section also shows that the building is not a simple vertical slab or tower. Its profile is shaped to create height, density, and an open courtyard condition at the same time.

### 2.2 4th Floor Plan

The 4th floor plan shows a large central courtyard surrounded by residential units and amenity spaces. The plan includes labeled amenities such as:

* Courtyard
* Swimming pool
* Basketball court
* Fitness studio
* Community room
* Game room

This drawing reveals that the courtyard is not leftover space. It is the central communal space around which residential and amenity programs are organized.

### 2.3 Courtyard / Amenity Plan

The courtyard plan shows landscape paths, planted zones, open areas, and shared recreational programs. The courtyard becomes an internal landscape that supports social and leisure activities.

Residential units are arranged around the courtyard, creating both inward-facing and outward-facing living conditions.

### 2.4 Massing Transformation Diagram

The massing diagram explains the design process. It begins with a simple block, inserts a courtyard, then lifts one corner to create a sloped tetrahedral form. This transformation produces a hybrid between a courtyard block and a high-rise tower.

The diagram is important because it shows that the building form is generated by spatial and environmental goals, not only by sculptural expression.

### 2.5 Aerial Context Image

The aerial image shows the building’s relationship with the Hudson River, Manhattan grid, nearby towers, and waterfront infrastructure. The building appears as a distinctive geometric object within the dense city fabric.

---

## 3. Vocabulary Extraction

### 3.1 Building Massing and Form

* Courtscraper
* Tetrahedral massing
* Sloped roof
* Triangular section
* Perimeter block
* High-rise corner
* Low-rise edge
* Hybrid tower-block form
* Skyline object
* Urban block

### 3.2 Residential Components

* Residential unit
* Apartment module
* Courtyard-facing unit
* City-facing unit
* River-facing unit
* Repeated residential floor
* Unit corridor
* Private balcony / terrace
* Window module

### 3.3 Courtyard and Communal Components

* Central courtyard
* Internal garden
* Communal open space
* Landscaped courtyard
* Swimming pool
* Basketball court
* Fitness studio
* Community room
* Game room
* Shared amenity floor
* Recreation space

### 3.4 Circulation and Service Components

* Residential corridor
* Vertical circulation core
* Elevator core
* Stair core
* Service zone
* Amenity circulation
* Perimeter circulation

### 3.5 Urban and Contextual Components

* Hudson River edge
* West Side Highway
* Manhattan grid
* Waterfront park
* Urban skyline
* 11th Avenue
* 12th Avenue
* West 57th Street
* Public open space

---

## 4. Quantity / Pattern Estimation

The following quantities and patterns are interpreted from the drawings and diagrams. Exact numbers should be confirmed through official project data if needed.

| Element           | Interpreted Quantity / Pattern                                                |
| ----------------- | ----------------------------------------------------------------------------- |
| Building Form     | One hybrid tetrahedral residential block                                      |
| Main Open Space   | One large internal courtyard                                                  |
| Residential Units | Repeated units arranged around the courtyard and along the outer perimeter    |
| Amenity Floor     | Shared amenities concentrated around the courtyard level                      |
| Building Height   | Slopes from a lower edge to a high corner                                     |
| Circulation       | Corridors and cores distributed along the residential perimeter               |
| Courtyard Program | Garden, pool, basketball court, community room, fitness studio, and game room |
| View Types        | River-facing, city-facing, and courtyard-facing units                         |

---

## 5. Spatial Relationship Descriptions

### 5.1 Building Mass → surrounds → Courtyard

The main building mass wraps around a central courtyard. This creates an inward-facing communal space protected from the surrounding city.

### 5.2 Courtyard → organizes → Residential Units

The courtyard acts as the spatial center of the project. Residential units are arranged around it, giving many units a visual or spatial relationship with the shared garden.

### 5.3 Sloped Roof → opens → Courtyard to Sky

The sloped roof form lowers one side of the mass and opens the courtyard toward the sky. This improves light access and reduces the sense of enclosure.

### 5.4 High-Rise Corner → concentrates → Residential Density

The building rises at one corner to provide high-rise density while allowing other parts of the building to remain lower and more open.

### 5.5 Perimeter Block → defines → Urban Edge

The building completes an urban block edge while also transforming the block into a three-dimensional residential form.

### 5.6 Amenity Spaces → activate → Courtyard

Shared amenities such as the swimming pool, basketball court, fitness studio, community room, and game room are located around the courtyard. These programs activate the internal open space.

### 5.7 Residential Corridor → connects → Apartment Modules

Corridors connect repeated apartment units along the perimeter of the courtyard and the exterior facade.

### 5.8 Massing Diagram → transforms → Block Typology

The massing diagram shows a transformation from a simple block to a courtyard block and then to a sloped courtscraper. This demonstrates a typological shift from flat block to hybrid tower.

### 5.9 Courtyard → mediates → City and Domestic Life

The courtyard provides a shared landscape that mediates between private housing units and the dense city surrounding the site.

### 5.10 Sloped Massing → balances → Views and Density

The sloped massing allows the building to maintain high density while improving daylight, views, and courtyard openness.

---

## 6. Overall Spatial Logic

VIA 57 West is organized around the transformation of a residential block into a three-dimensional courtyard tower.

The spatial logic can be summarized as:

**Urban Block → Courtyard Insertion → Corner Lifting → Sloped Courtscraper → Communal Garden Housing**

The project begins with the idea of a perimeter block, which provides a clear urban edge and internal courtyard. Instead of remaining a flat courtyard block, one corner is lifted to create a high-rise profile. This produces a hybrid form that combines:

1. **The density of a Manhattan high-rise**
2. **The communal space of a European courtyard**
3. **The skyline presence of a sculptural tower**
4. **The protected interior quality of a residential garden block**

The central courtyard is the key spatial element. It allows the large residential building to create an internal community space, while the sloped massing allows more light and openness to reach that courtyard.

---

## 7. Design Interpretation

The drawing analysis suggests that VIA 57 West is not only a visually iconic building. Its unusual form is tied to a clear housing strategy.

The most important design interpretation is that the project uses geometry to negotiate between conflicting urban demands:

* high residential density
* access to daylight
* access to views
* need for communal open space
* completion of the urban block
* creation of a skyline identity

The building’s triangular section and sloped roof are not only formal gestures. They help create a courtyard that is more open to light and sky than a conventional enclosed block.

The project also changes the role of the high-rise residential building. Instead of being a vertical isolated tower, it becomes a collective residential block with an internal landscape.

---

## 8. Preprocess Output Summary

### Key Spatial Elements

* Courtscraper
* Tetrahedral massing
* Sloped roof
* Central courtyard
* Residential unit
* Apartment module
* Residential corridor
* Vertical core
* Amenity floor
* Swimming pool
* Basketball court
* Fitness studio
* Community room
* Game room
* Urban block
* Hudson River edge

### Key Spatial Relationships

* Building Mass → surrounds → Courtyard
* Courtyard → organizes → Residential Units
* Sloped Roof → opens → Courtyard to Sky
* High-Rise Corner → concentrates → Residential Density
* Perimeter Block → defines → Urban Edge
* Amenity Spaces → activate → Courtyard
* Residential Corridor → connects → Apartment Modules
* Massing Diagram → transforms → Block Typology
* Courtyard → mediates → City and Domestic Life
* Sloped Massing → balances → Views and Density

### Main Design Logic

VIA 57 West uses a sloped tetrahedral form to combine a high-rise residential tower with a courtyard block. The central courtyard becomes the main communal space, while the sloped massing allows the building to maintain density, daylight, views, and urban presence.

---

## 9. Keywords for Precedent DNA

* courtscraper
* courtyard block
* high-rise residential
* tetrahedral massing
* sloped roof
* central courtyard
* communal garden
* amenity floor
* residential density
* Manhattan grid
* Hudson River edge
* urban block
* hybrid typology
* skyline identity
* inward-facing community

